package sheet

import "testing"

func TestTextFunctions(t *testing.T) {
	checkFormulas(t, fixture(t), []fnCase{
		{`=CONCATENATE("a", 1, TRUE)`, txt("a1TRUE")},
		{"=CONCATENATE(D1:D3)", txt("AppleBananaCherry")},
		{`=CONCAT(A1, "x")`, txt("10x")},
		{`=TEXTJOIN(", ", TRUE, A3:A5)`, txt("30, apple")},
		{`=TEXTJOIN("-", FALSE, A3:A5)`, txt("30-apple-")},
		{`=LEFT("hello", 2)`, txt("he")},
		{`=LEFT("hello")`, txt("h")},
		{`=LEFT("hi", 10)`, txt("hi")},
		{`=LEFT("hi", -1)`, ErrValue},
		{`=RIGHT("hello", 3)`, txt("llo")},
		{`=MID("spreadsheet", 7, 5)`, txt("sheet")},
		{`=MID("abc", 5, 2)`, txt("")},
		{`=MID("abc", 0, 2)`, ErrNum}, // as Sheets; Excel says #VALUE!
		{`=LEN("héllo")`, num(5)},
		{"=LEN(A1)", num(2)},
		{`=UPPER("abc")`, txt("ABC")},
		{`=LOWER("ABC")`, txt("abc")},
		{`=PROPER("hello wORLD it's")`, txt("Hello World It'S")},
		{`=TRIM("  a   b  ")`, txt("a b")},
		{`=SUBSTITUTE("a-b-c", "-", "+")`, txt("a+b+c")},
		{`=SUBSTITUTE("a-b-c", "-", "+", 2)`, txt("a-b+c")},
		{`=SUBSTITUTE("a-b-c", "-", "+", 5)`, txt("a-b-c")},
		{`=SUBSTITUTE("abc", "", "x")`, txt("abc")},
		{`=SUBSTITUTE("abc", "b", "x", 0)`, ErrValue},
		{`=REPLACE("abcdef", 2, 3, "X")`, txt("aXef")},
		{`=REPLACE("abc", 10, 1, "X")`, txt("abcX")},
		{`=REPLACE("abc", 0, 1, "X")`, ErrValue},
		{`=FIND("b", "abcb")`, num(2)},
		{`=FIND("b", "abcb", 3)`, num(4)},
		{`=FIND("B", "abc")`, ErrValue}, // case-sensitive
		{`=FIND("", "abc")`, num(1)},
		{`=FIND("a", "abc", 5)`, ErrValue},
		{`=SEARCH("B", "abc")`, num(2)},
		{`=SEARCH("b?d", "abcbxd")`, num(4)},
		{`=SEARCH("c*", "abc")`, num(3)},
		{`=SEARCH("z", "abc")`, ErrValue},
		{`=TEXT(1234.567, "$#,##0.00")`, txt("$1,234.57")},
		{`=TEXT(0.256, "0.0%")`, txt("25.6%")},
		{`=TEXT(F1, "yyyy-mm-dd")`, txt("2026-09-26")},
		{`=TEXT(F1, "dddd")`, txt("Saturday")},
		{`=TEXT(F3, "h:mm AM/PM")`, txt("2:30 PM")},
		{`=TEXT("12", "000")`, txt("012")},
		{`=TEXT("abc", "000")`, txt("abc")},
		{`=VALUE("$1,200")`, num(1200)},
		{`=VALUE("12%")`, num(0.12)},
		{`=VALUE("2026-09-26")`, num(46291)},
		{`=VALUE("")`, num(0)},
		{`=VALUE("abc")`, ErrValue},
		{"=VALUE(A1)", num(10)},
		{`=REPT("ab", 3)`, txt("ababab")},
		{`=REPT("ab", -1)`, ErrValue},
		{`=EXACT("a", "A")`, boolean(false)},
		{`=EXACT("a", "a")`, boolean(true)},
		{`=EXACT(10, "10")`, boolean(true)},
	})
}
