import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar, generated from the docs tree: folders by their
// _category_.json, pages by their front matter.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
