import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// A sidebar per section of the docs, each generated from its folder:
// the navbar picks the section, the sidebar lists its pages, so the two
// never show the same list. Folders order by their _category_.json, pages
// by their front matter.
const folders = [
  'getting-started',
  'sheets',
  'formulas',
  'files',
  'nushell',
  'agents',
  'terminal',
  'reference',
  'contributing',
];

const sidebars: SidebarsConfig = Object.fromEntries(
  folders.map((dir) => [dir, [{type: 'autogenerated', dirName: dir}]]),
);

export default sidebars;
